version: "3"

services:
  deepseek2api:
    container_name: deepseek2api
    image: ghcr.io/iidamie/deepseek2api:latest
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - "./config.json:/app/config.json"
      
  litellm:
    container_name: litellm_proxy
    image: ghcr.io/berriai/litellm:main-latest
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - "./litellm_config.yaml:/app/config.yaml"
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]
    depends_on:
      - deepseek2api